In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
import math

In [2]:
df = pd.read_feather("./outputs/Dormant_output.feather")
df

,lncRNA,diease,Algorithmic Value
0,NONHSAT000002.2,Abortion habitual,1.591137
1,NONHSAT000002.2,Acoustic neuroma,1.639681
2,NONHSAT000002.2,Acquired immunodeficiency syndrome,1.710313
3,NONHSAT000002.2,Acute coronary syndrome,1.642922
4,NONHSAT000002.2,Acute kidney failure,1.639706
...,...,...,...
3882751,NONHSAT007829.2,Childhood medulloblastoma,0.415320
3882752,NONHSAT007829.2,Differentiating neuroblastoma,0.415306
3882753,NONHSAT007829.2,Ganglioneuroblastoma,0.415556
3882754,NONHSAT007829.2,Ganglioneuroma,0.415369
3882755,NONHSAT007829.2,Carcinoma lung non-small-cell,0.513868

In [3]:
"""
Cell generated by Data Wrangler.
"""
def clean_data(df):
    # Sort by column: 'Algorithmic Value' (descending)
    df = df.sort_values(['Algorithmic Value'], ascending=[False])
    df["Ranking"] = range(1,len(df)+1)
    df = df[['Ranking'] + [col for col in df.columns if col != 'Ranking']]
    df['Normalized Algorithmic  Values'] = df['Algorithmic Value'].copy()
    
    # df.loc[df['Normalized Algorithmic  Values'] > 40, 'Normalized Algorithmic  Values'] = 40 + df['Normalized Algorithmic  Values'] * 1e-2
    df.loc[df['Normalized Algorithmic  Values'] < 3, 'Normalized Algorithmic  Values'] = 3 - df['Normalized Algorithmic  Values'] * 1e-1
    df.loc[df['Normalized Algorithmic  Values'] > 3, 'Normalized Algorithmic  Values'] = 3 + df['Normalized Algorithmic  Values'] * 1e-3
    df['Normalized Algorithmic  Values'] /= df['Normalized Algorithmic  Values'].max()

    return df

df_clean = clean_data(df.copy())
df_clean.head()

,Ranking,lncRNA,diease,Algorithmic Value,Normalized Algorithmic Values
3882516,1,NONHSAT007829.2,Cancer,329.630241,1.000000
3882002,2,NONHSAT013732.2,Cancer,199.861442,0.961026
3882512,3,NONHSAT007829.2,Vascular diseases,147.514495,0.945305
3881488,4,NONHSAT017055.2,Cancer,134.412445,0.941370
3880460,5,NONHSAT000708.2,Cancer,133.700118,0.941156